apiVersion: v1
kind: Service
metadata:
  name: yygang-api-service
spec:
  type: NodePort
  selector:
    app: yygang-api
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30088
